In [1]:
!pip install nltk scikit-learn gensim


In [2]:
import nltk
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec
from sklearn.datasets import fetch_20newsgroups


nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
data = fetch_20newsgroups(subset='train')

documents = data.data[:200]   # taking first 200 documents for faster execution

print("Number of documents:", len(documents))


Number of documents: 200


In [4]:
print("Sample Document:\n")
print(documents[0][:1000])


Sample Document:

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----







In [5]:
count_vectorizer = CountVectorizer(stop_words='english', max_features=1000)
bow_matrix = count_vectorizer.fit_transform(documents)

print("Vocabulary Size:", len(count_vectorizer.get_feature_names_out()))
print("BoW Matrix Shape:", bow_matrix.shape)


Vocabulary Size: 1000
BoW Matrix Shape: (200, 1000)


In [6]:
print("Bag of Words Matrix (first 5 documents):")
print(bow_matrix[:5].toarray())


Bag of Words Matrix (first 5 documents):
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
from sklearn.preprocessing import normalize

bow_norm_matrix = normalize(bow_matrix, norm='l1')

print("Normalized BoW Matrix (first 5 documents):")
print(bow_norm_matrix[:5].toarray())


Normalized BoW Matrix (first 5 documents):
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
tfidf_vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=1000
)

tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

print("TF-IDF Matrix Shape:", tfidf_matrix.shape)



TF-IDF Matrix Shape: (200, 1000)


In [9]:
print("TF-IDF Matrix (first 5 documents):")
print(tfidf_matrix[:5].toarray())


TF-IDF Matrix (first 5 documents):
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
tokenized_docs = [
    nltk.word_tokenize(doc.lower())
    for doc in documents
]

print("Tokenized Sample:")
print(tokenized_docs[0][:30])


Tokenized Sample:
['from', ':', 'lerxst', '@', 'wam.umd.edu', '(', 'where', "'s", 'my', 'thing', ')', 'subject', ':', 'what', 'car', 'is', 'this', '!', '?', 'nntp-posting-host', ':', 'rac3.wam.umd.edu', 'organization', ':', 'university', 'of', 'maryland', ',', 'college', 'park']


In [11]:
word2vec_model = Word2Vec(
    sentences=tokenized_docs,
    vector_size=100,
    window=5,
    min_count=5,
    workers=4
)



In [12]:
print("Embedding for word 'computer':")
print(word2vec_model.wv['computer'])


Embedding for word 'computer':
[ 0.1108021   0.2543818  -0.09371911  0.10363092  0.0898261  -0.63013774
  0.25789404  0.7425352  -0.28134975 -0.2525368  -0.0456038  -0.2019158
 -0.0807966   0.13433957  0.19867368 -0.21388838  0.11646807  0.07783142
 -0.17942002 -0.37409368 -0.05673266 -0.06642464  0.31247196  0.02218072
 -0.1432574  -0.05244043 -0.4035044  -0.07288165 -0.2570951   0.05375871
  0.23117235  0.0732932   0.06761187 -0.32136616 -0.04240607  0.4907012
  0.04687206 -0.07746893 -0.24862313 -0.5661437   0.11914483 -0.23582724
  0.10833932  0.09415808  0.22473513 -0.23665826 -0.30661947 -0.24094602
  0.26731786 -0.00185108  0.04395184 -0.45444426  0.00503196 -0.18426172
 -0.04115517 -0.14006063 -0.2998332  -0.2950795  -0.37135482 -0.0891514
  0.31426945 -0.10793183  0.22004311  0.07600257 -0.2691165   0.43598527
  0.29912654  0.3042423  -0.58854586  0.10453718 -0.26692092  0.19913952
  0.22719565  0.19793439  0.4577501   0.36375508  0.05060915  0.19408432
 -0.15791884 -0.0831807

In [13]:
print("Most similar words to 'computer':")
print(word2vec_model.wv.most_similar('computer'))


Most similar words to 'computer':
[('science', 0.9970350861549377), ('research', 0.9914214015007019), ('laboratory', 0.9893950819969177), ('internet', 0.9886048436164856), ('article-i.d', 0.9884203672409058), ('stratus', 0.985788106918335), ('department', 0.9836267232894897), ('space', 0.9835236072540283), ('seth', 0.9824529886245728), ('joe', 0.982280433177948)]
